DROP VIEW dbo.[ADC - Programmable];
DROP VIEW [dbo].[Audio - Amplifier];
DROP VIEW [dbo].[Battery Holder];
DROP VIEW [dbo].[Button - Push];
DROP VIEW [dbo].[Button - Slide];
DROP VIEW [dbo].[Button - Tactile];
DROP VIEW dbo.[Capacitor - Aluminium Polymer];
DROP VIEW [dbo].[Capacitor - Aluminium TH RA];
DROP VIEW [dbo].[Capacitor - Aluminium TH];
DROP VIEW dbo.[Capacitor - Aluminium];
DROP VIEW dbo.[Capacitor - Ceramic];
DROP VIEW dbo.[Capacitor - RF];
DROP VIEW dbo.[Capacitor - Tantalum Polymer];
DROP VIEW dbo.[Capacitor - Tantalum];
DROP VIEW [dbo].[Charger];
DROP VIEW dbo.[Chip LED];
DROP VIEW [dbo].[Connector - Backplane];
DROP VIEW [dbo].[Connector - Barrier Block];
DROP VIEW [dbo].[Connector - Card Edge];
DROP VIEW [dbo].[Connector - Dev Board];
DROP VIEW [dbo].[Connector - Modular w/Magnetics];
DROP VIEW dbo.[Connector - Modular];
DROP VIEW [dbo].[Connector - RF];
DROP VIEW [dbo].[Connector - Rectangular];
DROP VIEW [dbo].[Connector - SD];
DROP VIEW dbo.[Connector - Terminal Block];
DROP VIEW dbo.[Connector - USB];
DROP VIEW [dbo].[Digital Isolator];
DROP VIEW dbo.[Digital to Analogue Converter];
DROP VIEW dbo.[Diode - Rectifier];
DROP VIEW [dbo].[Diode - TVS];
DROP VIEW dbo.[Ferrite Chip];
DROP VIEW [dbo].[Gate Driver];
DROP VIEW [dbo].[Inductor - Power];
DROP VIEW dbo.[Inductor - RF];
DROP VIEW [dbo].[Interface - CAN];
DROP VIEW [dbo].[Interface - Differential Signal];
DROP VIEW [dbo].[Interface - Ethernet];
DROP VIEW [dbo].[Interface - RS485];
DROP VIEW dbo.[LCD Display - Graphic];
DROP VIEW [dbo].[LED Driver];
DROP VIEW [dbo].[Light Pipe];
DROP VIEW dbo.[MCU - ARM];
DROP VIEW dbo.[MCU - AVR];
DROP VIEW dbo.[Memory - EEPROM];
DROP VIEW dbo.[Memory - FLASH];
DROP VIEW [dbo].[Motor Driver - Controller];
DROP VIEW [dbo].[Motor Driver - Stepper];
DROP VIEW [dbo].[Mounting Bracket];
DROP VIEW [dbo].[Multiplexer];
DROP VIEW dbo.[N-Channel Dual FET Array];
DROP VIEW dbo.[N-Channel FET];
DROP VIEW [dbo].[Optoisolator];
DROP VIEW dbo.[Oscillator - Crystal];
DROP VIEW dbo.[Oscillator - MEMS];
DROP VIEW dbo.[Oscillator - TCXO];
DROP VIEW dbo.[Oscillator - VCTCXO];
DROP VIEW dbo.[Oscillator - XO];
DROP VIEW dbo.[P-Channel Dual FET Array];
DROP VIEW dbo.[P-Channel FET];
DROP VIEW [dbo].[Power Module];
DROP VIEW [dbo].[RF Amplifier];
DROP VIEW [dbo].[RF Antenna];
DROP VIEW dbo.[RF Attenuator];
DROP VIEW dbo.[RF Detector];
DROP VIEW [dbo].[RF Filter];
DROP VIEW [dbo].[RF Module];
DROP VIEW dbo.[RF Switch];
DROP VIEW [dbo].[Reset Supervisor];
DROP VIEW dbo.[Resistor - Chip];
DROP VIEW [dbo].[Resistor - Current Sense];
DROP VIEW dbo.[Resistor - Potentiometer];
DROP VIEW [dbo].[Sensor - Current];
DROP VIEW [dbo].[Sensor - IR];
DROP VIEW [dbo].[Sensor - Magnetic];
DROP VIEW [dbo].[Sensor - Motion];
DROP VIEW [dbo].[Sensor - Pressure];
DROP VIEW [dbo].[Sensor - Temperature];
DROP VIEW [dbo].[Sensor - Thermocouple];
DROP VIEW [dbo].[Switch - DIP];
DROP VIEW [dbo].[Test Point];
DROP VIEW [dbo].[Thermistor - NTC];
DROP VIEW [dbo].[Video];
DROP VIEW dbo.[Voltage Reference];
DROP VIEW dbo.[Voltage Regulator - Linear];
DROP VIEW [dbo].[Voltage Regulator - Switchmode];
